/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 08-jun.-2021 13:41:57 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `countries` CASCADE
;

DROP TABLE IF EXISTS `languages` CASCADE
;

DROP TABLE IF EXISTS `operators` CASCADE
;

DROP TABLE IF EXISTS `pay_options` CASCADE
;

DROP TABLE IF EXISTS `support_languages` CASCADE
;

DROP TABLE IF EXISTS `users` CASCADE
;

DROP TABLE IF EXISTS `users_operators` CASCADE
;

/* Create Tables */

CREATE TABLE `countries`
(
	`id_country` BIGINT NOT NULL AUTO_INCREMENT,
	`name_country` TEXT NOT NULL,
	`calling_code` VARCHAR(50) NULL,
	`alpha_code_2` VARCHAR(3) NOT NULL,
	`alpha_code_3` VARCHAR(4) NOT NULL,
	`register_date` DATETIME NOT NULL,
	`state` BOOL NOT NULL,
	CONSTRAINT `PK_country` PRIMARY KEY (`id_country` ASC)
)

;

CREATE TABLE `languages`
(
	`id_language` BIGINT NOT NULL AUTO_INCREMENT,
	`abreviation` VARCHAR(3) NOT NULL,
	`description` TEXT NOT NULL,
	`state` BOOL NOT NULL,
	CONSTRAINT `PK_languages` PRIMARY KEY (`id_language` ASC)
)

;

CREATE TABLE `operators`
(
	`id_operator` BIGINT NOT NULL AUTO_INCREMENT,
	`id_country` BIGINT NOT NULL,
	`name` TEXT NOT NULL,
	`pass` VARCHAR(50) NOT NULL,
	`phone_number` VARCHAR(150) NOT NULL,
	`email` VARCHAR(300) NOT NULL,
	`date` DATETIME NOT NULL,
	`state` INT NOT NULL,
	CONSTRAINT `PK_operator` PRIMARY KEY (`id_operator` ASC)
)

;

CREATE TABLE `pay_options`
(
	`id_pay_option` BIGINT NOT NULL AUTO_INCREMENT,
	`amount` DECIMAL(10,2) NOT NULL,
	`description` TEXT NOT NULL,
	`state` BOOL NOT NULL,
	CONSTRAINT `PK_pay_option` PRIMARY KEY (`id_pay_option` ASC)
)

;

CREATE TABLE `support_languages`
(
	`id_support_language` BIGINT NOT NULL AUTO_INCREMENT,
	`id_operator` BIGINT NULL,
	`id_language` BIGINT NOT NULL,
	`register_date` DATETIME NOT NULL,
	`state` BOOL NOT NULL,
	CONSTRAINT `PK_support_languages` PRIMARY KEY (`id_support_language` ASC)
)

;

CREATE TABLE `users`
(
	`id_user` BIGINT NOT NULL AUTO_INCREMENT,
	`id_pay_option` BIGINT NOT NULL,
	`id_language` BIGINT NOT NULL,
	`id_country` BIGINT NULL,
	`name` TEXT NOT NULL,
	`phone` VARCHAR(150) NOT NULL,
	`email` VARCHAR(300) NOT NULL,
	`pass` TEXT NOT NULL,
	`registration_date` DATETIME NOT NULL,
	`state` BOOL NOT NULL,
	CONSTRAINT `PK_usuarios` PRIMARY KEY (`id_user` ASC)
)

;

CREATE TABLE `users_operators`
(
	`id_user_operator` BIGINT NOT NULL AUTO_INCREMENT,
	`id_user` BIGINT NOT NULL,
	`id_operator` BIGINT NOT NULL,
	`comments` TEXT NULL,
	`qualification` INT NULL,
	`registration_date` DATETIME NOT NULL,
	`state` BOOL NOT NULL,
	CONSTRAINT `PK_user_operator` PRIMARY KEY (`id_user_operator` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `operators` 
 ADD CONSTRAINT `UK_operator_email` UNIQUE (`email` ASC)
;

ALTER TABLE `operators` 
 ADD CONSTRAINT `UK_operator_phone_number` UNIQUE (`phone_number` ASC)
;

ALTER TABLE `operators` 
 ADD INDEX `IXFK_operator_country` (`id_country` ASC)
;

ALTER TABLE `support_languages` 
 ADD INDEX `IXFK_support_languages_languages` (`id_language` ASC)
;

ALTER TABLE `support_languages` 
 ADD INDEX `IXFK_support_languages_operator` (`id_operator` ASC)
;

ALTER TABLE `users` 
 ADD CONSTRAINT `UK_user_email` UNIQUE (`email` ASC)
;

ALTER TABLE `users` 
 ADD CONSTRAINT `UK_user_phone` UNIQUE (`phone` ASC)
;

ALTER TABLE `users` 
 ADD INDEX `IXFK_user_languages` (`id_language` ASC)
;

ALTER TABLE `users` 
 ADD INDEX `IXFK_user_pay_option` (`id_pay_option` ASC)
;

ALTER TABLE `users_operators` 
 ADD INDEX `IXFK_user_operator_operator` (`id_operator` ASC)
;

ALTER TABLE `users_operators` 
 ADD INDEX `IXFK_user_operator_user` (`id_user` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `operators` 
 ADD CONSTRAINT `FK_operator_country`
	FOREIGN KEY (`id_country`) REFERENCES `countries` (`id_country`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `support_languages` 
 ADD CONSTRAINT `FK_support_languages_languages`
	FOREIGN KEY (`id_language`) REFERENCES `languages` (`id_language`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `support_languages` 
 ADD CONSTRAINT `FK_support_languages_operator`
	FOREIGN KEY (`id_operator`) REFERENCES `operators` (`id_operator`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `users` 
 ADD CONSTRAINT `FK_user_languages`
	FOREIGN KEY (`id_language`) REFERENCES `languages` (`id_language`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `users` 
 ADD CONSTRAINT `FK_user_pay_option`
	FOREIGN KEY (`id_pay_option`) REFERENCES `pay_options` (`id_pay_option`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `users_operators` 
 ADD CONSTRAINT `FK_user_operator_operator`
	FOREIGN KEY (`id_operator`) REFERENCES `operators` (`id_operator`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `users_operators` 
 ADD CONSTRAINT `FK_user_operator_user`
	FOREIGN KEY (`id_user`) REFERENCES `users` (`id_user`) ON DELETE No Action ON UPDATE No Action
;

SET FOREIGN_KEY_CHECKS=1 
;
