INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Afghanistan', '93','AF','AFG',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Åland Islands', '358','AX','ALA',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Albania', '355','AL','ALB',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Algeria', '213','DZ','DZA',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('American Samoa', '1684','AS','ASM',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Andorra', '376','AD','AND',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Angola', '244','AO','AGO',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Anguilla', '1264','AI','AIA',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Antarctica', '672','AQ','ATA',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Antigua and Barbuda', '1268','AG','ATG',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Argentina', '54','AR','ARG',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Armenia', '374','AM','ARM',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Aruba', '297','AW','ABW',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Australia', '61','AU','AUS',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Austria', '43','AT','AUT',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Azerbaijan', '994','AZ','AZE',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Bahamas', '1242','BS','BHS',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Bahrain', '973','BH','BHR',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Bangladesh', '880','BD','BGD',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Barbados', '1246','BB','BRB',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Belarus', '375','BY','BLR',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Belgium', '32','BE','BEL',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Belize', '501','BZ','BLZ',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Benin', '229','BJ','BEN',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Bermuda', '1441','BM','BMU',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Bhutan', '975','BT','BTN',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Bolivia (Plurinational State of)', '591','BO','BOL',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Bonaire, Sint Eustatius and Saba', '5997','BQ','BES',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Bosnia and Herzegovina', '387','BA','BIH',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Botswana', '267','BW','BWA',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Bouvet Island', '','BV','BVT',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Brazil', '55','BR','BRA',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('British Indian Ocean Territory', '246','IO','IOT',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('United States Minor Outlying Islands', '','UM','UMI',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Virgin Islands (British)', '1284','VG','VGB',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Virgin Islands (U.S.)', '1 340','VI','VIR',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Brunei Darussalam', '673','BN','BRN',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Bulgaria', '359','BG','BGR',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Burkina Faso', '226','BF','BFA',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Burundi', '257','BI','BDI',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Cambodia', '855','KH','KHM',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Cameroon', '237','CM','CMR',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Canada', '1','CA','CAN',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Cabo Verde', '238','CV','CPV',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Cayman Islands', '1345','KY','CYM',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Central African Republic', '236','CF','CAF',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Chad', '235','TD','TCD',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Chile', '56','CL','CHL',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('China', '86','CN','CHN',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Christmas Island', '61','CX','CXR',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Cocos (Keeling) Islands', '61','CC','CCK',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Colombia', '57','CO','COL',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Comoros', '269','KM','COM',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Congo', '242','CG','COG',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Congo (Democratic Republic of the)', '243','CD','COD',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Cook Islands', '682','CK','COK',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Costa Rica', '506','CR','CRI',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Croatia', '385','HR','HRV',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Cuba', '53','CU','CUB',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Curaçao', '599','CW','CUW',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Cyprus', '357','CY','CYP',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Czech Republic', '420','CZ','CZE',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Denmark', '45','DK','DNK',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Djibouti', '253','DJ','DJI',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Dominica', '1767','DM','DMA',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Dominican Republic', '1809','DO','DOM',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Dominican Republic', '1829','DO','DOM',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Dominican Republic', '1849','DO','DOM',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Ecuador', '593','EC','ECU',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Egypt', '20','EG','EGY',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('El Salvador', '503','SV','SLV',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Equatorial Guinea', '240','GQ','GNQ',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Eritrea', '291','ER','ERI',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Estonia', '372','EE','EST',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Ethiopia', '251','ET','ETH',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Falkland Islands (Malvinas)', '500','FK','FLK',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Faroe Islands', '298','FO','FRO',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Fiji', '679','FJ','FJI',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Finland', '358','FI','FIN',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('France', '33','FR','FRA',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('French Guiana', '594','GF','GUF',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('French Polynesia', '689','PF','PYF',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('French Southern Territories', '','TF','ATF',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Gabon', '241','GA','GAB',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Gambia', '220','GM','GMB',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Georgia', '995','GE','GEO',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Germany', '49','DE','DEU',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Ghana', '233','GH','GHA',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Gibraltar', '350','GI','GIB',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Greece', '30','GR','GRC',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Greenland', '299','GL','GRL',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Grenada', '1473','GD','GRD',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Guadeloupe', '590','GP','GLP',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Guam', '1671','GU','GUM',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Guatemala', '502','GT','GTM',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Guernsey', '44','GG','GGY',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Guinea', '224','GN','GIN',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Guinea-Bissau', '245','GW','GNB',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Guyana', '592','GY','GUY',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Haiti', '509','HT','HTI',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Heard Island and McDonald Islands', '','HM','HMD',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Holy See', '379','VA','VAT',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Honduras', '504','HN','HND',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Hong Kong', '852','HK','HKG',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Hungary', '36','HU','HUN',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Iceland', '354','IS','ISL',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('India', '91','IN','IND',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Indonesia', '62','ID','IDN',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Côte d Ivoire', '225','CI','CIV',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Iran (Islamic Republic of)', '98','IR','IRN',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Iraq', '964','IQ','IRQ',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Ireland', '353','IE','IRL',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Isle of Man', '44','IM','IMN',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Israel', '972','IL','ISR',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Italy', '39','IT','ITA',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Jamaica', '1876','JM','JAM',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Japan', '81','JP','JPN',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Jersey', '44','JE','JEY',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Jordan', '962','JO','JOR',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Kazakhstan', '76','KZ','KAZ',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Kazakhstan', '77','KZ','KAZ',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Kenya', '254','KE','KEN',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Kiribati', '686','KI','KIR',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Kuwait', '965','KW','KWT',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Kyrgyzstan', '996','KG','KGZ',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Lao People s Democratic Republic', '856','LA','LAO',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Latvia', '371','LV','LVA',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Lebanon', '961','LB','LBN',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Lesotho', '266','LS','LSO',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Liberia', '231','LR','LBR',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Libya', '218','LY','LBY',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Liechtenstein', '423','LI','LIE',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Lithuania', '370','LT','LTU',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Luxembourg', '352','LU','LUX',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Macao', '853','MO','MAC',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Macedonia (the former Yugoslav Republic of)', '389','MK','MKD',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Madagascar', '261','MG','MDG',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Malawi', '265','MW','MWI',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Malaysia', '60','MY','MYS',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Maldives', '960','MV','MDV',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Mali', '223','ML','MLI',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Malta', '356','MT','MLT',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Marshall Islands', '692','MH','MHL',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Martinique', '596','MQ','MTQ',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Mauritania', '222','MR','MRT',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Mauritius', '230','MU','MUS',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Mayotte', '262','YT','MYT',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Mexico', '52','MX','MEX',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Micronesia (Federated States of)', '691','FM','FSM',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Moldova (Republic of)', '373','MD','MDA',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Monaco', '377','MC','MCO',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Mongolia', '976','MN','MNG',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Montenegro', '382','ME','MNE',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Montserrat', '1664','MS','MSR',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Morocco', '212','MA','MAR',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Mozambique', '258','MZ','MOZ',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Myanmar', '95','MM','MMR',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Namibia', '264','NA','NAM',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Nauru', '674','NR','NRU',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Nepal', '977','NP','NPL',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Netherlands', '31','NL','NLD',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('New Caledonia', '687','NC','NCL',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('New Zealand', '64','NZ','NZL',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Nicaragua', '505','NI','NIC',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Niger', '227','NE','NER',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Nigeria', '234','NG','NGA',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Niue', '683','NU','NIU',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Norfolk Island', '672','NF','NFK',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Korea (Democratic People s Republic of)', '850','KP','PRK',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Northern Mariana Islands', '1670','MP','MNP',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Norway', '47','NO','NOR',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Oman', '968','OM','OMN',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Pakistan', '92','PK','PAK',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Palau', '680','PW','PLW',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Palestine, State of', '970','PS','PSE',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Panama', '507','PA','PAN',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Papua New Guinea', '675','PG','PNG',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Paraguay', '595','PY','PRY',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Peru', '51','PE','PER',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Philippines', '63','PH','PHL',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Pitcairn', '64','PN','PCN',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Poland', '48','PL','POL',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Portugal', '351','PT','PRT',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Puerto Rico', '1787','PR','PRI',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Puerto Rico', '1939','PR','PRI',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Qatar', '974','QA','QAT',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Republic of Kosovo', '383','XK','KOS',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Réunion', '262','RE','REU',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Romania', '40','RO','ROU',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Russian Federation', '7','RU','RUS',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Rwanda', '250','RW','RWA',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Saint Barthélemy', '590','BL','BLM',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Saint Helena, Ascension and Tristan da Cunha', '290','SH','SHN',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Saint Kitts and Nevis', '1869','KN','KNA',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Saint Lucia', '1758','LC','LCA',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Saint Martin (French part)', '590','MF','MAF',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Saint Pierre and Miquelon', '508','PM','SPM',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Saint Vincent and the Grenadines', '1784','VC','VCT',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Samoa', '685','WS','WSM',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('San Marino', '378','SM','SMR',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Sao Tome and Principe', '239','ST','STP',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Saudi Arabia', '966','SA','SAU',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Senegal', '221','SN','SEN',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Serbia', '381','RS','SRB',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Seychelles', '248','SC','SYC',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Sierra Leone', '232','SL','SLE',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Singapore', '65','SG','SGP',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Sint Maarten (Dutch part)', '1721','SX','SXM',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Slovakia', '421','SK','SVK',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Slovenia', '386','SI','SVN',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Solomon Islands', '677','SB','SLB',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Somalia', '252','SO','SOM',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('South Africa', '27','ZA','ZAF',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('South Georgia and the South Sandwich Islands', '500','GS','SGS',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Korea (Republic of)', '82','KR','KOR',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('South Sudan', '211','SS','SSD',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Spain', '34','ES','ESP',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Sri Lanka', '94','LK','LKA',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Sudan', '249','SD','SDN',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Suriname', '597','SR','SUR',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Svalbard and Jan Mayen', '4779','SJ','SJM',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Swaziland', '268','SZ','SWZ',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Sweden', '46','SE','SWE',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Switzerland', '41','CH','CHE',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Syrian Arab Republic', '963','SY','SYR',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Taiwan', '886','TW','TWN',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Tajikistan', '992','TJ','TJK',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Tanzania, United Republic of', '255','TZ','TZA',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Thailand', '66','TH','THA',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Timor-Leste', '670','TL','TLS',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Togo', '228','TG','TGO',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Tokelau', '690','TK','TKL',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Tonga', '676','TO','TON',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Trinidad and Tobago', '1868','TT','TTO',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Tunisia', '216','TN','TUN',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Turkey', '90','TR','TUR',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Turkmenistan', '993','TM','TKM',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Turks and Caicos Islands', '1649','TC','TCA',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Tuvalu', '688','TV','TUV',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Uganda', '256','UG','UGA',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Ukraine', '380','UA','UKR',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('United Arab Emirates', '971','AE','ARE',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('United Kingdom of Great Britain and Northern Ireland', '44','GB','GBR',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('United States of America', '1','US','USA',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Uruguay', '598','UY','URY',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Uzbekistan', '998','UZ','UZB',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Vanuatu', '678','VU','VUT',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Venezuela (Bolivarian Republic of)', '58','VE','VEN',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Viet Nam', '84','VN','VNM',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Wallis and Futuna', '681','WF','WLF',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Western Sahara', '212','EH','ESH',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Yemen', '967','YE','YEM',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Zambia', '260','ZM','ZMB',NOW(),TRUE);
INSERT INTO countries (name_country,calling_code,alpha_code_2,alpha_code_3,register_date,state) VALUES ('Zimbabwe', '263','ZW','ZWE',NOW(),TRUE);


INSERT INTO languages (abreviation,description,state)
VALUES('EN','ENGLISH',TRUE);
INSERT INTO languages (abreviation,description,state)
VALUES('ES','SPANISH',TRUE);
INSERT INTO languages (abreviation,description,state)
VALUES('JP','JAPANESE',TRUE);


INSERT INTO pay_options (amount,description,state)
VALUES(9.99,'$ 9.99 \n- 10 asissted calls included \n- 0.99 each additional call.',TRUE);
INSERT INTO pay_options (amount,description,state)
VALUES(19.99,'$ 19.99 \n- 30 asissted calls included \n- 0.99 each additional call.',TRUE);